const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~SPInHKSb#FxbXTcme-ndYy1HFUwO9zQAZst3EK1VAax-Nh13B-K4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
